### ISSUE TITLE
Unknown column '0' in 'order clause'

### ISSUE THREAD

**Issue by jojomanoke** [ACFBentveld/Laravel-datatables#7] opened 2019-02-21 10:40 UTC
If I use `\DataTables::model(new Product)->get();` I am getting a `Unknown column '0' in 'order clause'` error

**Comment by wimurk** [comment] 2019-02-25 10:27
Hello @jojomanoke 
can you give me a snippet of your code? I can't reproduce this issue

**Comment by jojomanoke** [comment] 2019-02-25 10:47
```
public function index(){
    $products = \DataTables::model(new Product)->get();
    return view('some.view')->with(compact('$products'))
}
```
Since I don't have the code in my project anymore, this is all I remember. I followed the docs.

**Comment by wimurk** [comment] 2019-02-25 10:54
This won't work at all since \DataTables returns false by default when called incorrect. 
As explained in the docs, call the package without assigning it to a variable.

```php
public function index(){
    \DataTables::model(new Product)->get();
    return view('some.view');
}
```
Also update to the lastest version. `2.*`

**Closed by wimurk** 2019-02-25 10:54 UTC
Labels: invalid, question

**Comment by jojomanoke** [comment] 2019-02-25 11:05
**ProductsController.php**
```
public function index(){
    \DataTables::model(new Product)->get();
    return view('some.view');
}
```
**some.view.blade.php**
```
<table id="datatable" class="table">
    <thead>
        <tr>
            <th>#</th>
            <th>name</th>
        </tr>
    </thead>
</table>
```
**index.js**
```
$(document).ready(function() {
    $('#datatable').DataTable({
        "processing": true,
        "serverSide": true,
        "ajax": location.href, 
        "columns": [ //define the keys
            { "data": "key1" },
            { "data": "key2" },
            //etc
        ],
    });
} );
```
This produces my error

**Comment by wimurk** [comment] 2019-02-25 11:11
Can you take a screenshot of your error?

**Comment by jojomanoke** [comment] 2019-02-25 11:17
> Since I don't have the code in my project anymore, this is all I remember. I followed the docs.
I deleted the package so I can't saddly...

**Comment by wimurk** [comment] 2019-02-25 11:23
Since i can't reproduce the error and don't have any information on the error. This issue will stay closed and no further action is required.
